### ISSUE TITLE
9.01 Setbackdrop issue #2 

### ISSUE THREAD

**Issue by Pharou80** [LoneWanderer-GH/CoolLine#12]
2x CoolLine\core.lua:207: attempt to call method 'SetBackdrop' (a nil value)
[string "@CoolLine\core.lua"]:207: in function <CoolLine\core.lua:184>
[string "@CoolLine\core.lua"]:291: in function `?'
[string "@CoolLine\core.lua"]:3: in function <CoolLine\core.lua:2>

Locals:
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <table> {
 edgeSize = 16
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
self = CoolLine {
 0 = <userdata>
 SPELLS_CHANGED = <function> defined @CoolLine\core.lua:495
 SPELL_UPDATE_COOLDOWN = <function> defined @CoolLine\core.lua:557
 PixelSnapDisabled = true
 PLAYER_ENTERING_WORLD = <function> defined @CoolLine\core.lua:297
 frames = <table> {
 }
 NewCooldown = <function> defined @CoolLine\core.lua:397
 UNIT_PET = <function> defined @CoolLine\core.lua:630
 PET_BAR_UPDATE_COOLDOWN = <function> defined @CoolLine\core.lua:605
 border = <unnamed> {
 }
 PLAYER_LEAVING_WORLD = <function> defined @CoolLine\core.lua:306
 bg = <unnamed> {
 }
 SPELL_UPDATE_CHARGES = <function> defined @CoolLine\core.lua:557
 PET_BATTLE_CLOSE = <function> defined =[C]:-1
 PET_BATTLE_OPENING_START = <function> defined =[C]:-1
 spells = <table> {
 }
 ClearCooldown = <function> defined @CoolLine\core.lua:316
 chargespells = <table> {
 }
 UNIT_EXITED_VEHICLE = <function> defined @CoolLine\core.lua:670
 UNIT_ENTERED_VEHICLE = <function> defined @CoolLine\core.lua:661
 ACTIONBAR_UPDATE_COOLDOWN = <function> defined @CoolLine\core.lua:641
 updatelook = <function> defined @CoolLine\core.lua:184
 cooldowns = <table> {
 }
 specialspells = <table> {
 }
 BAG_UPDATE_COOLDOWN = <function> defined @CoolLine\core.lua:570
 UNIT_SPELLCAST_FAILED = <function> defined @CoolLine\core.lua:683
}
db = <table> {
 bgcolor = <table> {
 }
 border = "None"
 borderinset = 6
 h = 49
 fontsize = 14
 block = <table> {
 }
 iconplus = 8
 spellcolor = <table> {
 }
 nospellcolor = <table> {
 }
 inactivealpha = 0.500000
 bordercolor = <table> {
 }
 w = 285
 y = -7
 x = 469
 dbinit = 3
 statusbar = "Gloss"
 bordersize = 16
 font = "Doris PP"
 fontcolor = <table> {
 }
 activealpha = 1
}
smed = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 SetDefault = <function> defined @ArkInventory\Externals\SharedMedia\LibSharedMedia-3.0.lua:293
 GetDefault = <function> defined @ArkInventory\Externals\SharedMedia\LibSharedMedia-3.0.lua:289
 LOCALE_BIT_ruRU = 2
 UnregisterAllCallbacks = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 SetGlobal = <function> defined @ArkInventory\Externals\SharedMedia\LibSharedMedia-3.0.lua:280
 GetGlobal = <function> defined @ArkInventory\Externals\SharedMedia\LibSharedMedia-3.0.lua:276
 List = <function> defined @ArkInventory\Externals\SharedMedia\LibSharedMedia-3.0.lua:266
 HashTable = <function> defined @ArkInventory\Externals\SharedMedia\LibSharedMedia-3.0.lua:262
 MediaTable = <table> {
 }
 RegisterCallback = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 IsValid = <function> defined @ArkInventory\Externals\SharedMedia\LibSharedMedia-3.0.lua:258
 LOCALE_BIT_zhCN = 4
 UnregisterCallback = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Fetch = <function> defined @ArkInventory\Externals\SharedMedia\LibSharedMedia-3.0.lua:251
 DefaultMedia = <table> {
 }
 Register = <function> defined @ArkInventory\Externals\SharedMedia\LibSharedMedia-3.0.lua:218
 MediaList = <table> {
 }
 LOCALE_BIT_koKR = 1
}
backdrop = <table> {
 edgeSize = 16
}
section = 0
iconsize = 0
SetValue = nil
SetValueVR = <function> defined @CoolLine\core.lua:41
SetValueV = <function> defined @CoolLine\core.lua:37
SetValueHR = <function> defined @CoolLine\core.lua:33
SetValueH = <function> defin

**Comment by LoneWanderer-GH** [comment]
same as #10
