### ISSUE TITLE
[BUG][TBC Pre-patch]

### ISSUE THREAD

**Issue by Zyno** [LoneWanderer-GH/CoolLine#18]
**Describe the bug**
Lua Error
Message: Interface\AddOns\CoolLine\core.lua:3: attempt to perform arithmetic on local 'version' (a string value)
Time: Thu May 20 11:14:21 2021
Count: 1
Stack: Interface\AddOns\CoolLine\core.lua:3: attempt to perform arithmetic on local 'version' (a string value)
[string "@Interface\AddOns\CoolLine\core.lua"]:3: in main chunk

Locals: ORANGEY = ""
LIGHTRED = ""
version = "2.5.1"
build = "38707"
date = "May 17 2021"
build_toc_version = 20501
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'version' (a string value)"

**To Reproduce**
Log in with the character to the world.

** Software verrsions (please complete the following information):**
 - OS: [Win 10]
 - WoW game version: [TBC pre-patch]
 - Addon Version: [CoolLine-9.1.000-beta-2-bcc]

**Comment by godsyn** [comment]
To get working for classic_tbc:
in core.lua:
line 3:
-- `local major_version = floor(version / 10000)`
++ `local major_version = floor((select(4, GetBuildInfo())) / 10000)`

Line 361:
--     `if not IS_CLASSIC then`
++     `if IS_RETAIL_RELEASE then`

**Comment by Red86** [comment]
Can confirm that the above suggestion works

**Comment by LoneWanderer-GH** [comment]
Hi, code typo indeed.

There is work in progress to improve classic/tbc/retail code version management and packaging.

**Comment by LoneWanderer-GH** [comment]
Basically the version check code is/was ulgy as hell and not tested.

Please have a look at this beta release https://github.com/LoneWanderer-GH/CoolLine/releases/tag/9.1.000-beta3

It should land to curse forge **as beta** in a few hours.

**Comment by godsyn** [comment]
All is working with 9.1.000-beta3-bcc. Thanks!
