### ISSUE TITLE
is there any way to add some spells into blacklist? thank you

### ISSUE THREAD

**Issue by WOWLZG** [LoneWanderer-GH/CoolLine#21]
ctrl+f 'blacklist' didn't find anything, so there is no blacklist or something like that?

**Comment by LoneWanderer-GH** [comment]
A bit late on this ...

The addon takes spellbook spells + items into account.
What would you filter ? spells ? items ? both ?

**Comment by HORSE666666** [comment]
spells like revive battle pet (not sure if the spellname is right), items like Hearthstone ... these are no need to watch in combat and the icons will shelter others.
for now, I modified a WA found in WAGO which is similar to COOLLINE but can add some spells to blacklist.
wago link: https://wago.io/chlTNgi3I. it's for classic, but retail can also work with a little modification
by the way, the wa has an interesting feature : when use a not ready spell, the icon will enlarge and glow

**Comment by LoneWanderer-GH** [comment]
> by the way, the wa has an interesting feature : when use a not ready spell, the icon will enlarge and glow

As far as I can tell, CoolLine does this natively in Retail, probably due to the way the WowAPI is used and works in retail.
This would be a separate feature.

> add some spells to blacklist

I'll think about this, but I'm not sure of when I could do that. However, there is a LUA table defining blacklist spell names or id, see the saved variables file for coolline.

**Comment by LoneWanderer-GH** [comment]
Well, I digged a bit ... turns out the feature already exists, but you can't see what is in the blacklist in-game, only in the savedvariables file.

`/coolline <spellid or itemid>`

will toggle filtering

**Comment by HORSE666666** [comment]
Got it. Thank you!
