### ISSUE TITLE
typo in core.lua 

### ISSUE THREAD

**Issue by Road-block** [LoneWanderer-GH/CoolLine#4]
[core.lua#L620](https://github.com/LoneWanderer-GH/CoolLine/blob/0104dc9cb40796fe2c38d19666fdfbf0c06dd50c/core.lua#L620)

`bookType` ▶️ `btype`

**Comment by LoneWanderer-GH** [comment]
Thanks for reporting this.

I could not spot it since I mainly use classic.
- Can you tell if it is retail and/or classic ?
- Do you have any more info on what was your error (bugsack/swatter report ?)

It opened a fix branch https://github.com/LoneWanderer-GH/CoolLine/tree/fix-issue-%234

**Comment by Road-block** [comment]
Classic.  
There is no Lua error, it's a logic bug because `bookType` is an unintended global read.  
It will be `nil` unless some other addon is leaking a variable with that name.

The result is that `bookType == BOOKTYPE_SPELL` will always be false regardless what the `btype` (which is the intended variable) is.

**Comment by LoneWanderer-GH** [comment]
well, thats sounds like a old coding typo (https://github.com/LoneWanderer-GH/CoolLine/blame/0104dc9cb40796fe2c38d19666fdfbf0c06dd50c/core.lua#L620) this means the code is maybe not even reachable.

Di you ran a (lua) code checker by any chance ?

**Comment by LoneWanderer-GH** [comment]
Typo fix delivered and released (see #5 )
