### ISSUE TITLE
[BUG] [Classic] Warrior's skill: Bloodrage, isn't showing up on coolline.

### ISSUE THREAD

**Issue by LoneWanderer-GH** [LoneWanderer-GH/CoolLine#7]
Message received on curseforge:
Warrior's skill: Bloodrage, isn't showing up on coolline.

https://classic.wowhead.com/spell=2687/bloodrage

No more info yet.
I could be related to #4, I've asked user to test the #5 branch

**Comment by Systern** [comment]
Did not work in the test branch. One more piece of information... I actually have Improved Bloodrage on my Warrior. Unsure if that could be related to it not showing up on CoolLine.

**Comment by LoneWanderer-GH** [comment]
Its working for a level 10 warrior
![image](https://user-images.githubusercontent.com/19716859/96591853-00333280-12e8-11eb-9e9e-fb8e44dc1044.png)

**Comment by LoneWanderer-GH** [comment]
I made a few tests with level 60 guildies, they don't have any issues with this.
Closing it.
