### ISSUE TITLE
[BUG] [CLASSIC] No pet cooldowns for warlock

### ISSUE THREAD

**Issue by LoneWanderer-GH** [LoneWanderer-GH/CoolLine#8]
> youzilyj
> Posted 7 hours ago
> #1
> Hi there,
> 
> I really appreciate your work updating this addon. I couldn't leave a comment on the actual page so I'm sending you this message to report a bug. The addon does not show pet's cooldown at all. I'm a warlock btw. Thanks again.
> 
>  
> Best

**Comment by LoneWanderer-GH** [comment]
It might be related to how the spellbook is managed to get spells with cooldowns.

**Comment by youjunli** [comment]
Thanks for looking into this. I've only tested it on the felhunter. With pet cooldowns enabled, there are still no cooldowns for spell lock or devour magic.
